---
# This task takes care of the PHP installation and configuration

- name: php5.yml | Check if php5-fpm is already installed
  command: dpkg -s php5-fpm
  ignore_errors: yes
  register: php5fpm
  failed_when: "'is not installed' in php5fpm.stderr"

# Uncomment this if you want to see the content of php5fpm
#- debug: var=php5fpm

# Install packages defined in vars.yml ensuring that the latest version in installed
# This means that once the packages are installed it will keep them updated
# Switch latest to present if you don't want automatic updates
- name: php5.yml | Install PHP Packages
  apt: pkg={{ item }} state=latest
  with_items: php_packages
