VAGRANTFILE_API_VERSION = "2"

############################################################
# VARIABLES

# Vagrant template box name
VG_BOX_NAME = "debian_wheezy_770_64bit"

# Local virtual machine for development
VB_DEV_VM_NAME = "dev.ariadne.vm"
VB_DEV_VM_IP = "192.168.51.10"
############################################################



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Vagrant settings for the development vm
    config.vm.define VB_DEV_VM_NAME, primary: true do |devel|

        # Vagrant box name. This the Vagrant template (created by Packer) from which the vagrant vm will be generated
        devel.vm.box = VG_BOX_NAME

        # Hostname for the generated vagrant box
        devel.vm.hostname = VB_DEV_VM_NAME

        # Sets the IP
        devel.vm.network "private_network", ip: VB_DEV_VM_IP

        # NFS settings
        devel.vm.synced_folder "../../projects", "/vagrant", type: "nfs"

        devel.vm.provider "virtualbox" do |vb|
            vb.name = VB_DEV_VM_NAME

            ## Don't boot with headless mode => shows virtualbox UI. Uncomment for troubleshooting.
            #vb.gui = true

            # Use VBoxManage to customize the VM. For example to change memory:
            vb.customize ["modifyvm", :id, "--memory", "512"]
            vb.customize ["modifyvm", :id, "--cpus", "1"]
            vb.customize ["modifyvm", :id, "--ioapic", "on"]
        end
    end

end
